name = "esencity"
main = ".vercel/output/static/_worker.js/index.js"
compatibility_date = "2025-06-01"
compatibility_flags = ["nodejs_compat"]

[vars]
APPS_SCRIPT_URL = "https://script.google.com/macros/s/AKfycbw_Go4iLu20hhWaCqVqCewPsILwiB8qe4A5xo1K3IqCA_27_fVGWFTT03lbF2ml6UUs1g/exec"
NEXT_PUBLIC_APPS_SCRIPT_URL = "https://script.google.com/macros/s/AKfycbw_Go4iLu20hhWaCqVqCewPsILwiB8qe4A5xo1K3IqCA_27_fVGWFTT03lbF2ml6UUs1g/exec"
NEXT_PUBLIC_INSTAGRAM_USERNAME = "esenc.ity"
NEXT_PUBLIC_SITE_NAME = "EsencityPeluquería"
NEXT_PUBLIC_SITE_URL = "https://esencity.com"

[observability]
enabled = true

kv_namespaces = [
  { binding = "NEXT_CACHE_WORKERS_KV", id = "675acaa4bc4e4172a853f50792dcee92" }
]

[assets]
directory = ".vercel/output/static"
